{% set name = "spcqe" %}
{% set version = "0.0.1a0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: .. 

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.9
    - numpy
    - cvxpy
    - scikit-learn
    - tqdm

test:
  imports:
    - spcqe
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Smooth periodic consistent quantile estimation
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pluflou
